### ISSUE TITLE
How do I install this on Windows 10 Pro?

### ISSUE THREAD

**Issue by ainsleyrutterford** [JamesDanielOReilly/Practical-Bioinformatics#1]
How *is* this possible?

Thank **you**

**Comment by JamesDanielOReilly** [comment]
Found a solution here : https://itstillworks.com/13330347/how-to-install-microsoft-word-xp-on-vista

**Comment by ainsleyrutterford** [comment]
> Found a solution here : https://itstillworks.com/13330347/how-to-install-microsoft-word-xp-on-vista

Th**an**k yo**u** so m*uc*h
